[STRAITSX-4634] set approval for all for pbm owners
StraitsX/Orchid-PBM pull request #13
Opened 2023-06-20 00:05 UTC by jacobshan

[Context]
- [jira link](https://fazzfinancial.atlassian.net/browse/STRAITSX-4634)

[Approach]
* add setApprovalForAllForPBMOwners function to allow owner or whiltelisted approvers to set approval to issuerHelper on behalf of the user

2023-06-27 04:19 UTC, ChiuWeiYi approved these changes

2023-07-12 04:18 UTC, alcedo requested changes

2023-07-12 04:18 UTC, alcedo commented on Pilot5SFFNov2023/test/PBM.test.js
> +          .setApprovalForAllForPBMOwners(
put in more addresses to test?

2023-07-12 16:28 UTC, jacobshan commented on Pilot5SFFNov2023/contracts/PBM.sol
> +            _setApprovalForAll(pbmOwners[i], operator, approved);
```
    function setApprovalForAll(address operator, bool approved) public virtual override {
        _setApprovalForAll(_msgSender(), operator, approved);
    }
```

`setApprovalForAll` is grant/revoke approval to `operator` to transfer the caller's tokens. here the caller isn't the token owner(user)

2023-07-13 06:32 UTC, alcedo approved these changes
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia2.giphy.com%2Fmedia%2FnxM7IbxDeTRxC%2Fgiphy.gif&token=lgtm" data-gitmeme-token="lgtm"><img src="https://media2.giphy.com/media/nxM7IbxDeTRxC/giphy.gif" title="Created by gitme.me with /lgtm"/></a>

2023-07-13 06:33 UTC, alcedo commented
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FpCO5tKdP22RC8%2Fgiphy.gif&token=nice" data-gitmeme-token="nice"><img src="https://media3.giphy.com/media/pCO5tKdP22RC8/giphy.gif" title="Created by gitme.me with /nice"/></a>

2023-07-18 03:41 UTC, merged