[STRAITSX-47060] hero NFT
StraitsX/Orchid-PBM pull request #14
Opened 2023-07-11 17:52 UTC by jacobshan

[Context]
- ERC1155 hero NFT 
- make base URI upgradable
- only owner and whitelisted address(PBM contract in pilot6 ) can mint hero NFT

[Note]
- token id is unique to each merchant.
- image url in the metadata should be provided by Grab
- metadata json better host on a dedicated github/s3

2023-07-12 04:56 UTC, alcedo requested changes

2023-07-12 04:56 UTC, alcedo commented on heroNFT2023SEP/contracts/HeroNFT.sol
> +        "https://raw.githubusercontent.com/StraitsX/Orchid-PBM/STRAITSX-4706/commemorative_nft/heroNFT2023SEP/metadata/";
created one here https://github.com/StraitsX/NFT/blob/main/README.md#introduction

2023-07-12 04:56 UTC, alcedo commented on heroNFT2023SEP/metadata/0.json
> +{"description": "cute dog", "name": "SUSHI THE SHIBA", "attributes": [{"trait_type": "Base", "value": "Canine"}], "image": "https://fazzfinancialgroup.notion.site/image/https%3A%2F%2Fs3-us-west-2.ama
can be moved also  https://github.com/StraitsX/NFT/blob/main/README.md#introduction

2023-07-12 04:56 UTC, alcedo commented on heroNFT2023SEP/metadata/0.json
> +{"description": "cute dog", "name": "SUSHI THE SHIBA", "attributes": [{"trait_type": "Base", "value": "Canine"}], "image": "https://fazzfinancialgroup.notion.site/image/https%3A%2F%2Fs3-us-west-2.ama
Can change to this also

{
   "description":"Hero NFT",
   "name":"SG Hero Merchant series 2023",
   "attributes":[
      {
         "trait_type":"Base",
         "value":"Cultural - Food"
      }
   ],
   "image":"https://fazzfinancialgroup.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F3632850a-85ff-418b-a399-9fe6cf6ab9ce%2FUntitled.png?id=2df5203c-ca21-4a09-8395-e624e6d3b259&table=block&spaceId=bdc391a7-c326-437a-bb1e-2ce2ad0e7da0&width=1720&userId=&cache=v2"
}

2023-07-12 04:56 UTC, alcedo commented on heroNFT2023SEP/scripts/deploy.js
> +  const heroNFT = await hre.ethers.deployContract('HeroNFT');
include the script to do minting and mint to address?

2023-07-12 16:19 UTC, jacobshan commented on heroNFT2023SEP/contracts/HeroNFT.sol
> +    string baseURI = "https://raw.githubusercontent.com/StraitsX/NFT/main/heroNFT2023SEP/heroNFT2023SEP/";
don't have access to push PR to the repo yet. once it's pushed and merged this link will be working.

2023-07-13 06:43 UTC, alcedo approved these changes
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia4.giphy.com%2Fmedia%2FHw8vYF4DNRCKY%2Fgiphy.gif&token=ship" data-gitmeme-token="ship"><img src="https://media4.giphy.com/media/Hw8vYF4DNRCKY/giphy.gif" title="Created by gitme.me with /ship"/></a> it

2023-07-13 06:43 UTC, alcedo commented on heroNFT2023SEP/README.md
> +This ERC1155 behaves like a ERC721, ensuring (address, token_id) is unique and only 1 of such pair can ever exist in the smart contract.
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FpCO5tKdP22RC8%2Fgiphy.gif&token=nice" data-gitmeme-token="nice"><img src="https://media3.giphy.com/media/pCO5tKdP22RC8/giphy.gif" title="Created by gitme.me with /nice"/></a>

2023-07-13 06:43 UTC, alcedo commented on heroNFT2023SEP/contracts/HeroNFT.sol
> +    string baseURI = "https://raw.githubusercontent.com/StraitsX/NFT/main/heroNFT2023SEP/heroNFT2023SEP/";
<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2F3oz8xQQP4ahKiyuxHy%2Fgiphy.gif&token=ok" data-gitmeme-token="ok"><img src="https://media3.giphy.com/media/3oz8xQQP4ahKiyuxHy/giphy.gif" title="Created by gitme.me with /ok"/></a>

2023-07-13 06:50 UTC, alcedo commented
![image](https://github.com/StraitsX/Orchid-PBM/assets/1174679/f3a4bbe6-9e5d-4eb3-8d9f-58028d365b7c)

2023-07-14 08:30 UTC, merged