[STRAITSX-4707] feat(heronft): hero airdrop upon first successful payment
StraitsX/Orchid-PBM pull request #16
Opened 2023-07-14 22:49 UTC by jacobshan

- migrate to hardhat
- added heroMerchant management in the PBMAddressList contract
- mint heroNFT upon first successful payment to heroMerchant

2023-07-17 15:28 UTC, donbader commented on Pilot6July2023/contracts/PBM.sol
> +import "./IHeroNFT.sol";
Why this hero NFT is PBM's concern?

2023-07-17 15:31 UTC, donbader commented on Pilot6July2023/hardhat.config.js
> +            url: `https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_ACCESS_TOKEN}`,
Prefer making it full RPC url instead of this `ALCHEMY_ACCESS_TOKEN`

So that we can switch between different node provider

2023-07-17 15:38 UTC, donbader commented on Pilot6July2023/test/PBM.test.js
> +      expect(events.length).to.equal(1);
Also write event expectations maybe?

2023-07-17 15:40 UTC, donbader commented on Pilot6July2023/test/PBMTransfer.test.js
> +const { assert, expect } = require('chai');
If you want to split files for different scenarios.
maybe it's better to put it under a folder
```
|_ test
  |_ PBM
    |_ minting.test.js
    |_ transfer.test.js
    |_ ...
```

2023-07-17 16:03 UTC, donbader commented on Pilot6July2023/test/heroNFTTransfer.test.js
> +    it('batch Transfer to hero merchant successfully mint heroNFT to user', async () => {
Also test whether batch transfer would double NFT

2023-07-17 16:06 UTC, donbader commented on Pilot6July2023/contracts/HeroNFT.sol
> +    ) public onlyWhitelisted {
why is it not only owner

2023-07-17 16:08 UTC, donbader commented on Pilot6July2023/contracts/HeroNFT.sol
> +    function mintBatch(
where would we use this method?

2023-07-17 16:12 UTC, donbader commented on Pilot6July2023/contracts/IPBMAddressList.sol
> +    function addHeroMerchant(address[] memory addresses, uint256[] memory token_ids) external;
```suggestion
    function addHeroMerchants(address[] memory addresses, uint256[] memory token_ids) external;
```

2023-07-17 16:12 UTC, donbader commented on Pilot6July2023/contracts/IPBMAddressList.sol
> +    function removeHeroMerchant(address[] memory addresses) external;
```suggestion
    function removeHeroMerchants(address[] memory addresses) external;
```

2023-07-17 16:16 UTC, donbader commented on Pilot6July2023/contracts/PBMAddressList.sol
> +    function addHeroMerchant(address[] memory addresses, uint256[] memory token_ids) external override onlyOwner {
Is it possible that token ids are invalid?

2023-07-17 16:17 UTC, donbader commented on Pilot6July2023/contracts/HeroNFT.sol
> +    function mint(address account, uint256 id, uint256 amount, bytes memory data) public onlyWhitelisted {
Is it possible that if my wallet is whitelisted, I can mint for Jacob

2023-07-18 03:34 UTC, alcedo requested changes

2023-07-18 03:34 UTC, alcedo commented on Pilot6July2023/test/heroNFTTransfer.test.js
> +
add a test that transfers to Non hero merchant should not airdrop heroNFT to user.

2023-07-18 03:34 UTC, alcedo commented on Pilot6July2023/contracts/HeroNFT.sol
> +    function mint(address account, uint256 id, uint256 amount, bytes memory data) public onlyWhitelisted {
yes correct u can do that.

2023-07-18 03:34 UTC, alcedo commented on Pilot6July2023/contracts/HeroNFT.sol
> +    function mint(address account, uint256 id, uint256 amount, bytes memory data) public onlyWhitelisted {
yes correct u can do that. @donbader

2023-07-18 03:44 UTC, jacobshan commented on Pilot6July2023/contracts/HeroNFT.sol
> +pragma solidity ^0.8.9;
yes. it is for test cases. hardhat can't seem to import contracts from folders other than the contracts folder in the current directory

2023-07-18 03:45 UTC, jacobshan commented on Pilot6July2023/contracts/HeroNFT.sol
> +pragma solidity ^0.8.9;
any better way to handle this? 🤔

2023-07-18 03:45 UTC, jacobshan commented on Pilot6July2023/test/PBMTransfer.test.js
> +const { assert, expect } = require('chai');
okay I will address this in the following PR.

2023-07-18 03:47 UTC, jacobshan commented on Pilot6July2023/deployments/mumbai/.chainId
> +80001
auto generated by hardhat deploy package. it is used to track deployments so that we do have to re deploy everytime we run the tests.

2023-07-18 03:52 UTC, jacobshan commented on Pilot6July2023/contracts/HeroNFT.sol
> +    function mintBatch(
mostly used to mint to grab wallets for testing purpose.

2023-07-18 03:57 UTC, jacobshan commented on Pilot6July2023/migrations/2_initialise_pbm.js
> +  await pbm.initialise(address, expiryDate, addressListDeployment.address);
I addressed this in the following PR alr.

2023-07-18 06:50 UTC, alcedo commented on Pilot6July2023/contracts/HeroNFT.sol
> +pragma solidity ^0.8.9;
dont have to do this now but there's 2 option

1. rmb to cp and paste updates always
2. git sub modules https://dev.to/jjokah/submodules-a-git-repo-inside-a-git-repo-36l9

2023-07-20 18:53 UTC, jacobshan commented on Pilot6July2023/contracts/IPBMAddressList.sol
> +    function addHeroMerchant(address[] memory addresses, uint256[] memory token_ids) external;
decided not to change it. heroMerchant here is more of an "adjective" than a noun.

2023-07-21 09:24 UTC, alcedo approved these changes

2023-07-22 15:32 UTC, merged