[STRAITSX-4809] uobdsgd support
StraitsX/Orchid-PBM pull request #18
Opened 2023-07-17 17:50 UTC by jacobshan

[Context]
- add support for uobdsgd

[Approach]
- add spotType to token config to specify XSGD or DSGD
- add swap contract to swap DSGD to XSGD upon safeTransferFrom so merchant always receives XSGD
- modify Spot contract to take in dynamic params for testing

[Todo]

- [ ] Fix deploy script

2023-07-18 14:51 UTC, ChiuWeiYi reviewed
Can I say DSGD refers to digital SGD, which UOB issues?

And we want to allow DSGD swap XSGD

2023-07-20 09:38 UTC, alcedo commented
> Can I say DSGD refers to digital SGD, which UOB issues and we want to allow DSGD swap XSGD?

yes correct @ChiuWeiYi

2023-07-20 15:08 UTC, alcedo requested changes

2023-07-20 15:09 UTC, alcedo approved these changes

2023-07-20 17:27 UTC, merged